version: "3"
services:
  app:
    build:
      context: ./
      dockerfile: docker/app/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    container_name: app
  db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: db